title: Panshul Saraswat
logo: "/image/profile.png"  # Update the path if needed
font-family: 'Times New Roman'
description: >
  Analytical and detail-oriented data analyst with a Master's in Business Analytics. Experienced in data analysis, project management, and technical troubleshooting. Passionate about using innovative solutions to enhance data-driven processes.

